language: node_js

node_js:
- "4"

sudo: false

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm; fi
install:
  - npm install -g codecov
  - npm install
script:
  - npm test && codecov
  - npm run build
after_success:
  - if [[ "$TRAVIS_BRANCH" == "next" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
      ./script/release.sh;
      ./script/deploy.sh;
    fi
